pool:
  name: Azure Pipelines
steps:
- script: |
   npm install
   cd python_files
   pip install requirements.txt
  displayName: 'Install Dependencies'

- script: |
   npm run build
  displayName: 'Build the Project'

