pool:
  name: Azure Pipelines
steps:
- script: |
   cd python_files
   pip install requirements.txt
   npm install

  displayName: 'Install Dependencies'

- script: |
   npm run build
  displayName: 'Build the Project'

