pool:
  name: Azure Pipelines
steps:
- script: |

   pip install -r requirements.txt
   npm install

  displayName: 'Install Dependencies'

- script: |
   npm run build
  displayName: 'Build the Project'

